allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: false
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  re2: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ngrx/signals@22.0.0'
overrides:
  'eslint-plugin-tsdoc>@typescript-eslint/utils': 8.66.0
  listr2: 10.2.1
peerDependencyRules:
  allowedVersions:
    'tsconfck>typescript': '>=5.0.0 <7.0.0'
    '@angular/fire>firebase-tools': '15.27.0'
