name: CI main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-main-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  full:
    uses: ./.github/workflows/ci-checks.yml
    with:
      full: true
