name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 11.17.0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      # This enables task distribution via Nx Cloud.
      - run: pnpm exec nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Prepend commands with "nx record --" to record their logs to Nx Cloud.
      - run: pnpm exec nx record -- pnpm exec nx format:check --base="remotes/origin/main"
      - run: pnpm exec nx run-many -t lint test build
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/docs/features/ci-features/self-healing-ci
      - run: pnpm exec nx fix-ci
        if: always()
